# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# See "https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html"
# 24 is 1.13-pre, 25 is 1.13.2, 26 is 1.14.2, 27 is 1.14.3, 28 is 1.14.4
loaderVersion="[28,)" #mandatory

# A URL to refer people to when problems occur with this mod
# issueTrackerURL="http://github.com/YourName/Your-Mod-Name/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="merluzos"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory
# A display name for the mod
displayName="Merluzo's random stuff" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://github.com/YourName/Your-Mod-Name/update.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
# displayURL="http://github.com/YourName/Your-Mod-Name" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="merluzos.png" #optional
# A text field displayed in the mod UI
credits="Thanks to Cadiboo for his great example mod -> https://github.com/Cadiboo/Example-Mod"
# A text field displayed in the mod UI
authors="@Capitangolo"
# The description text for the mod (multi line!) (#mandatory)
description='''
Random blocks and stuff for the Aparticos.com livestreams
'''

[[dependencies.merluzos]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.merluzos]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"
